- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Extensions/AnalyzerExtensions.cs
- src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedAnalyzer.cs
- src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Usage/DisposableVariableNotDisposedTests.cs
I dealed with several interesting cases, like explicit implementation of IDisposable, and had some fun with data flow analysis as well. Read the tests for better understanding.
This is the end result:
Docs are updated: http://code-cracker.github.io/diagnostics/CC0022.html
> IDisposable variable not assigned to a field is not being disposed

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Usage/IPAddressAnalyzer.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Usage/IPAddressAnalyzerTests.cs
> fixes - #188 - Validate IPAddress.Parse from System.Net

- .gitignore
- .nuget/packages.config
- CodeCracker.CSharp.sln
- README.md
- appveyor.yml
- test/CSharp/CodeCracker.Test/packages.config
- test/CSharp/RunCodeCoverage.ps1
Related to #99 
Don't touch this PR, I am working on it. It is here only so I can test the build process.
> Add code coverage

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Extensions/AnalyzerExtensions.cs
- src/CSharp/CodeCracker/Usage/UnusedParametersAnalyzer.cs
- src/CSharp/CodeCracker/Usage/UnusedParametersCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Usage/UnusedParametersTests.cs
> Remove unused parameters: analyzer and fix

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Style/RemoveTrailingWhitespaceAnalyzer.cs
- src/CSharp/CodeCracker/Style/RemoveTrailingWhitespaceCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Style/RemoveTrailingWhitespaceTests.cs
I used a syntax tree analyzer to be able to be performant
Closes #201
> Remove trailing whitespace analyzer and code fix

- src/CSharp/CodeCracker/Usage/DisposablesShouldCallSuppressFinalizeAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/DisposablesShouldCallSuppressFinalizeTests.cs
CC0029 should be reported for explicit IDisposable.Dispose implementation
> reporting CC0029 for explicit IDisposable.Dispose implementation

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Reliability/UseConfigureAwaitFalseAnalyzer.cs
- src/CSharp/CodeCracker/Reliability/UseConfigureAwaitFalseCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Helpers/TestHelpers.cs
- test/CSharp/CodeCracker.Test/Reliability/UseConfigureAwaitFalseTests.cs
> Implemented UseConfigureAwaitFalse analyzer and code fix

- src/VisualBasic/CodeCracker/CodeCracker.vbproj
- src/VisualBasic/CodeCracker/Style/InterfaceNameAnalyzer.vb
- src/VisualBasic/CodeCracker/Style/InterfaceNameCodeFixProvider.vb
- test/VisualBasic/CodeCracker.Test/CodeCracker.Test.vbproj
- test/VisualBasic/CodeCracker.Test/Style/InterfaceNameTests.vb
VB Translation of InterfaceName style code fix.
> VB-InterfaceName translation

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Refactoring/IntroduceFieldFromConstructorCodeFixProvider.cs
- src/CSharp/CodeCracker/Refactoring/IntroduceFieldFromConstructorCodeFixProviderAll.cs
- test/CSharp/CodeCracker.Test/Refactoring/IntroduceFieldFromConstructorTest.cs
> Fix bug on CC0071

- src/VisualBasic/CodeCracker/CodeCracker.vbproj
- src/VisualBasic/CodeCracker/Usage/ArgumentExceptionAnalyzer.vb
- src/VisualBasic/CodeCracker/Usage/ArgumentExceptionCodeFixProider.vb
- test/VisualBasic/CodeCracker.Test/CodeCracker.Test.vbproj
- test/VisualBasic/CodeCracker.Test/Usage/ArgumentExceptionTests.vb
> VB Translation of Usage - ArgumentException

- src/CSharp/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.cs
"RemovePrivateMethodNeverUsedAnalyzer (CC0068) throwing cast exception #276"
> Remove private method never used

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Usage/RemoveUnreachableCodeCodeFixProvider.cs
- src/CSharp/CodeCracker/Usage/RemoveUnreachableCodeFixAllProvider.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Usage/RemoveUnreachableCodeTest.cs
- test/Common/CodeCracker.Test.Common/Verifiers/CodeFixVerifier.cs
- test/Common/CodeCracker.Test.Common/Verifiers/DiagnosticVerifier.cs
Closes #21
Also several improvements on the fix all infrastructure verification code.
> Remove unreachable code

- src/CSharp/CodeCracker/Usage/UnusedParametersAnalyzer.cs
- src/VisualBasic/CodeCracker/CodeCracker.vbproj
- src/VisualBasic/CodeCracker/Usage/UnusedParametersAnalyzer.vb
- src/VisualBasic/CodeCracker/Usage/UnusedParametersCodeFixProvider.vb
- test/VisualBasic/CodeCracker.Test/CodeCracker.Test.vbproj
- test/VisualBasic/CodeCracker.Test/Usage/UnusedParameterTests.vb
> Vb usage unused parameter

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Refactoring/NumericLiteralAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/NumericLiteralCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Refactoring/NumericLiteralTests.cs
>  Convert numeric literal from decimal to hex and hex to decimal

- src/CSharp/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/RemovePrivateMethodNeverUsedAnalyzerTest.cs
I would like to check if this is enough. So, I will do that in VB.
> Solving bug for csharp impl #290

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Usage/RemoveUnusedVariablesAnalyzer.cs
- src/CSharp/CodeCracker/Usage/RemoveUnusedVariablesCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Usage/RemoveUnusedVariablesTest.cs
> Add remove unused variable #23

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Refactoring/MergeNestedIfAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/MergeNestedIfCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Refactoring/MergeNestedIfTest.cs
> Merge nested if statements

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Usage/StringFormatArgsAnalyzer.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Usage/StringFormatArgsTests.cs
> String format args

- build.targets.ps1
ref #304 , Add flag to send full sources
> Send code to coveralls with --full-sources flag

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Refactoring/SplitIntoNestedIfAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/SplitIntoNestedIfCodeFixProvider.cs
- src/CSharp/CodeCracker/Refactoring/SplitIntoNestedIfFixAllProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Refactoring/SplitIntoNestedIfTests.cs
> Split if into nested ifs

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Refactoring/ComputeExpressionAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/ComputeExpressionCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Refactoring/ComputeExpressionTests.cs
> Add compute value of an expression analyzer

- src/CSharp/CodeCracker/Style/ObjectInitializerAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/ObjectInitializerTests.cs
> Fix bug in CC0008 when accessing declaring variable

- .nuget/packages.config
- build.targets.ps1
I couldn't get the build to work locally until I made the following changes
(the packages.config changes were actually made by VS2015 as it restored the packages)
> broken build

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Usage/RedundantFieldAssignmentAnalyzer.cs
- src/CSharp/CodeCracker/Usage/RedundantFieldAssignmentCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Usage/RedundantFieldAssignmentTests.cs
closes #9
PR created from Greece during my vacations! :) :sunny:
> Add analyzer/fix for redudant field initializers

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Performance/UseStaticRegexIsMatchAnalyzer.cs
- src/CSharp/CodeCracker/Performance/UseStaticRegexIsMatchCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Performance/UseStaticRegexIsMatchTests.cs
As suggested, it provides 3 possible code fix: use static, use compiled, use both.
> Add UseStaticRegexIsMatch Analyzer, closes #297

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Style/UseStringEmptyAnalyzer.cs
- src/CSharp/CodeCracker/Style/UseStringEmptyCodeFixProvider.cs
- src/CSharp/CodeCracker/Style/UseStringEmptyCodeFixProviderAll.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Style/UseStringEmptyTests.cs
> Use StringEmpty

- test/Common/CodeCracker.Test.Common/Helpers/DiagnosticVerifier.Helper.cs
- test/Common/CodeCracker.Test.Common/Verifiers/CodeFixVerifier.cs
> Fixes some little docs errors.

- src/CSharp/CodeCracker/Usage/CallExtensionMethodAsExtensionAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/CallExtensionMethodAsExtensionTests.cs
> Fix InvalidOperationException on CallExtensionMethodAsExtensionAnalyzer

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Style/UseEmptyStringAnalyzer.cs
- src/CSharp/CodeCracker/Style/UseEmptyStringCodeFixProvider.cs
- src/CSharp/CodeCracker/Style/UseEmptyStringCodeFixProviderAll.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Style/UseEmptyStringTest.cs
This implements #354 Use "" instead of String.Empty. Let me know if there are any remarks.
> #354 use literal empty string instead of string.empty

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Usage/RemoveRedundantElseClauseAnalyzer.cs
- src/CSharp/CodeCracker/Usage/RemoveRedundantElseClauseCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Usage/RemoveRedundantElseClauseTests.cs
> Analyzer for issue #355

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Style/SwitchToAutoPropAnalyzer.cs
- src/CSharp/CodeCracker/Style/SwitchToAutoPropCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Style/SwitchToAutoPropTests.cs
- test/CSharp/CodeCracker.Test/Usage/NoPrivateReadonlyFieldTest.cs
- test/CSharp/CodeCracker.Test/Usage/ReadonlyFieldTests.cs
- test/Common/CodeCracker.Test.Common/Helpers/DiagnosticVerifier.Helper.cs
- test/Common/CodeCracker.Test.Common/Helpers/Extensions.cs
- test/Common/CodeCracker.Test.Common/Verifiers/CodeFixVerifier.cs
- test/Common/CodeCracker.Test.Common/Verifiers/DiagnosticVerifier.cs
I had to update the infrastructure to enable to set C# and VB language versions.
The first commit is just the analyzer, the second is the infrastructure changes.
> Create auto property analyzer and fix

- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Style/ObjectInitializerAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/ObjectInitializerTests.cs
> Fix obj initializer bug with indirect initialization

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Refactoring/ChangeAnyToAllAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/ChangeAnyToAllCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Refactoring/ChangeAnyToAllTests.cs
- test/Common/CodeCracker.Test.Common/Helpers/Extensions.cs
closes #31
I did Any to All and All to Any and also added several other special cases.
> Add Convert Any to all and vice versa refactoring

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Design/MakeMethodStaticAnalyzer.cs
- src/CSharp/CodeCracker/Design/MakeMethodStaticCodeFixProvider.cs
- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Design/MakeMethodStaticTests.cs
> Make method static

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityCodeFixProvider.cs
- src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInFieldType.cs
- src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInIndexerParameter.cs
- src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInIndexerReturnType.cs
- src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInMethodParameter.cs
- src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInMethodReturnType.cs
- src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInPropertyType.cs
- src/Common/CodeCracker.Common/Extensions/AnalyzerExtensions.cs
- src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
- src/Common/CodeCracker.Common/Properties/Resources.resx
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Design/InconsistentAccessibilityTests.FieldPropertyType.cs
- test/CSharp/CodeCracker.Test/Design/InconsistentAccessibilityTests.MethodIndexerParameter.cs
- test/CSharp/CodeCracker.Test/Design/InconsistentAccessibilityTests.MethodIndexerReturnType.cs
Fixes `CS0052`, `CS0053`, `CS0054`, `CS0055` in #381 
Implementation with unit tests for `CS0052`, `CS0053`, `CS0054`, `CS0055` compiler errors.
> CS0052, CS0053, CS0054, CS0055 code fix

- src/CSharp/CodeCracker/Design/CopyEventToVariableBeforeFireAnalyzer.cs
- test/CSharp/CodeCracker.Test/Design/CopyEventToVariableBeforeFireTests.cs
- test/Common/CodeCracker.Test.Common/FixAllDiagnosticProvider.cs
> Fix Error in Test Source Code

- src/CSharp/CodeCracker/Style/StringFormatCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/StringFormatTests.cs
> Fix issue 410

- src/CSharp/CodeCracker/Maintainability/XmlDocumentationCreateMissingParametersCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Maintainability/XmlDocumentationTests.cs
Fix #412 when there were no summary or param element, now its working in any case.
> Fix bug on XmlDocumentationCodeFixProvider

- src/CSharp/CodeCracker/Usage/RemoveUnusedVariablesCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Usage/RemoveUnusedVariablesTest.cs
> Fix Bug #419

- nuget.config
- src/VisualBasic/CodeCracker/Design/NameOfAnalyzer.vb
- test/VisualBasic/CodeCracker.Test/Design/NameOfTests.vb
Pull into master for bug fix for #420.
> Vb design name of

- src/VisualBasic/CodeCracker/Refactoring/AllowMembersOrderingAnalyzer.vb
- src/VisualBasic/CodeCracker/Refactoring/AllowMembersOrderingCodeFixProvider.Base.vb
- src/VisualBasic/CodeCracker/Refactoring/ParameterRefactoryAnalyzer.vb
- src/VisualBasic/CodeCracker/Reliability/UseConfigureAwaitFalseCodeFixProvider.vb
Fixes issue #440 and 2 errors caught when testing manual editing scenarios.
> Fixes #440 and 2 runtime errors

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Usage/ValidateColorAnalyzer.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
- src/Common/CodeCracker.Common/Properties/Resources.resx
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Usage/ValidateColorTests.cs
Closes #1
Validate color from System.Drawing.ColorTranslator.FromHtml
> Added ValidateColor Analizer

- test/CSharp/CodeCracker.Test/Style/AlwaysUseVarTests.cs
Added a test to check if AlwaysUseVar code fix works when fixing all instances.
Effort for #352.
> Added a fix all test to the AlwaysUseVarTests

- src/CSharp/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/RemovePrivateMethodNeverUsedAnalyzerTest.cs
Fix bug #478 by adding check for explicit interface specifier of a method declaration.
> Fix for bug #478

- src/CSharp/CodeCracker/Design/MakeMethodStaticAnalyzer.cs
- test/CSharp/CodeCracker.Test/Design/MakeMethodStaticTests.cs
- test/Common/CodeCracker.Test.Common/Verifiers/DiagnosticVerifier.cs
Also fixed a typo (in a separate commit)
> Fix #479: don't raise CC0091 on explicit interface implementation

- src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityCodeFixProvider.cs
- src/CSharp/CodeCracker/Design/MakeMethodStaticAnalyzer.cs
- src/CSharp/CodeCracker/Performance/EmptyFinalizerAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/ParameterRefactoryAnalyzer.cs
- src/CSharp/CodeCracker/Style/RemoveCommentedCodeAnalyzer.cs
- src/CSharp/CodeCracker/Usage/CallExtensionMethodAsExtensionAnalyzer.cs
- src/CSharp/CodeCracker/Usage/DisposablesShouldCallSuppressFinalizeAnalyzer.cs
- src/VisualBasic/CodeCracker/Usage/DisposablesShouldCallSuppressFinalizeAnalyzer.vb
- test/Common/CodeCracker.Test.Common/Verifiers/CodeFixVerifier.cs
- test/Common/CodeCracker.Test.Common/Verifiers/DiagnosticVerifier.cs
Updated uses of .Count() with either .Count or .Length accordingly.
> Fix issue #489

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Performance/ReturnTaskInsteadOfAwaitAnalyzer.cs
- src/CSharp/CodeCracker/Performance/ReturnTaskInsteadOfAwaitCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
- src/Common/CodeCracker.Common/Properties/Resources.resx
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Performance/ReturnTaskInsteadOfAwaitTests.cs
- test/Common/CodeCracker.Test.Common/Helpers/Extensions.cs
This PR introduces the ReturnTaskInsteadOfAwaitAnalyzer.
Discussed in #151. 
I also added 26 Unit tests to cover both the analyzer and CodeFix. 
Please let me know what you think :)
> Return task instead of await

- runTestsCS.ps1
- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Refactoring/LoopToLinqAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/LoopToLinqCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
- src/Common/CodeCracker.Common/Properties/Resources.resx
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Refactoring/LoopToLinqTests.cs
> Change foreach to linq

- src/CSharp/CodeCracker/Style/SwitchToAutoPropCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/SwitchToAutoPropTests.cs
This pull request fixes #500 and #512. 
I included a unit test for #514. I was unsure how to fix that issue so I will just leave it in.
Please feel free to comment on this.
> CC0017 ignores field assignments

- src/CSharp/CodeCracker/Design/MakeMethodStaticCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Design/MakeMethodStaticTests.cs
Fix #486 by adding the static modifier without the method declaration's trivia and add the trivia back in after the modifier has been added.  This seems like a work around to a Roslyn bug since adding the modifier works OK if there is already a modifier present.
> Fix #486 by adding the static modifier without trivia

- src/CSharp/CodeCracker/Performance/StringBuilderInLoopAnalyzer.cs
- src/VisualBasic/CodeCracker/Performance/StringBuilderInLoopAnalyzer.vb
- test/CSharp/CodeCracker.Test/Performance/StringBuilderInLoopTests.cs
- test/VisualBasic/CodeCracker.Test/Performance/StringBuilderInLoopTests.vb
Fix for #485 by testing for the string being declared within the loop.
> Fix for #485 string builder in loop

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Refactoring/ExtractClassToFileAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/ExtractClassToFileCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Refactoring/ExtractClassToFileTests.cs
- test/Common/CodeCracker.Test.Common/Verifiers/CodeFixVerifier.cs
> Issue #382

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Performance/SealMemberAnalyzer.cs
- src/CSharp/CodeCracker/Performance/SealMemberCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
- src/Common/CodeCracker.Common/Properties/Resources.resx
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Performance/SealMemberTests.cs
- test/Common/CodeCracker.Test.Common/Verifiers/CodeFixVerifier.cs
> Seal members if possible

- src/CSharp/CodeCracker/Design/NameOfAnalyzer.cs
- src/CSharp/CodeCracker/Design/NameOfCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- src/VisualBasic/CodeCracker/Design/NameOfAnalyzer.vb
- src/VisualBasic/CodeCracker/Design/NameOfCodeFixProvider.vb
- test/CSharp/CodeCracker.Test/Design/NameOfTests.cs
- test/VisualBasic/CodeCracker.Test/Design/NameOfTests.vb
> Make external nameof disabled and on a different diagnostic id

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Usage/UnusedParametersCodeFixAllProvider.cs
- src/CSharp/CodeCracker/Usage/UnusedParametersCodeFixProvider.cs
- src/VisualBasic/CodeCracker/CodeCracker.vbproj
- src/VisualBasic/CodeCracker/Usage/UnusedParametersAnalyzer.vb
- src/VisualBasic/CodeCracker/Usage/UnusedParametersCodeFixAllProvider.vb
- src/VisualBasic/CodeCracker/Usage/UnusedParametersCodeFixProvider.vb
- test/CSharp/CodeCracker.Test/Usage/UnusedParametersTests.cs
- test/VisualBasic/CodeCracker.Test/Usage/UnusedParameterTests.vb
Two updates:
Enable params with UnusedParameters (#533)
Also reenable the analyzer for VB
Fix all in UnusedParameters (#534)
Also update VB analyzer to send props to code fix and update code fix making it more effient when reporting the fix
> Fix unused parameters

- src/CSharp/CodeCracker/Style/ObjectInitializerAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/ObjectInitializerTests.cs
> Fixed CC0008 and CC0009 (ObjectInitializer) when used with collection.

- src/VisualBasic/CodeCracker/Style/TernaryOperatorCodeFixProviders.vb
- test/VisualBasic/CodeCracker.Test/Style/TernaryOperatorTests.vb
Finally got my branch cleaned-up and the tests passing with allow new compiler diagnostics.
> Fix for #468 ternary code fix with nullables

- src/CSharp/CodeCracker/Usage/ReadonlyFieldAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/ReadonlyFieldTests.cs
This PR fixes #544 by checking if the assignment of a field in a constructor is done in a lambda.
> Fixes #544 by ignoring assignment of fields in Lambda in constructor

- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedAnalyzer.cs
- src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Usage/DisposableVariableNotDisposedTests.cs
> Fix incorrect diagnostic on anonymous funcions for DisposableVariableNotDisposed

- src/CSharp/CodeCracker/Style/SwitchToAutoPropCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/SwitchToAutoPropTests.cs
> Issue Fixed #548

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Style/SwitchToAutoPropCodeFixAllProvider.cs
- src/CSharp/CodeCracker/Style/SwitchToAutoPropCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/SwitchToAutoPropTests.cs
- test/Common/CodeCracker.Test.Common/Verifiers/CodeFixVerifier.cs
> Fix switch to auto property fix all

- src/CSharp/CodeCracker/Design/UseInvokeMethodToFireEventAnalyzer.cs
- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- test/CSharp/CodeCracker.Test/Design/UseInvokeMethodToFireEventTests.cs
> Dont raise diag if checked for null in UseInvokeMethodToFireEventAnalyzer

- src/CSharp/CodeCracker/Style/TernaryOperatorCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/TernaryOperatorTests.cs
> Fix ternary operator code fix when types differ

- src/CSharp/CodeCracker/Style/ObjectInitializerAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/ObjectInitializerTests.cs
> Fix ObjectInitializerAnalyzer to work with self assignment

- src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Usage/DisposableVariableNotDisposedTests.cs
> Moving leading trivia from variable declaration to using statement (fixes #577)

- src/CSharp/CodeCracker/Design/MakeMethodStaticAnalyzer.cs
- test/CSharp/CodeCracker.Test/Design/MakeMethodStaticTests.cs
> Remove webforms application lifecicle methods from MakeMethodStaticAnalyzer

- src/VisualBasic/CodeCracker/Design/CatchEmptyCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Design/EmptyCatchBlockCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Design/NameOfCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Design/StaticConstructorExceptionCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Performance/MakeLocalVariableConstWhenPossibleCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Performance/RemoveWhereWhenItIsPossibleAnalyzer.vb
- src/VisualBasic/CodeCracker/Performance/RemoveWhereWhenItIsPossibleCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Performance/SealedAttributeCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Performance/StringBuilderInLoopAnalyzer.vb
- src/VisualBasic/CodeCracker/Performance/StringBuilderInLoopCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Refactoring/ParameterRefactoryCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Reliability/UseConfigureAwaitFalseCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Style/InterfaceNameCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Usage/ArgumentExceptionAnalyzer.vb
- src/VisualBasic/CodeCracker/Usage/ArgumentExceptionCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Usage/DisposableFieldNotDisposedAnalyzer.vb
- src/VisualBasic/CodeCracker/Usage/DisposableFieldNotDisposedCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Usage/DisposablesShouldCallSuppressFinalizeCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Usage/MustInheritClassShouldNotHavePublicConstructorsCodeFixProvider.vb
- src/VisualBasic/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.vb
- src/VisualBasic/CodeCracker/Usage/RemovePrivateMethodNeverUsedCodeFixProvider.vb
> #348 Update VB code fixes to reduce work done in register code fix method

- src/CSharp/CodeCracker/Style/AlwaysUseVarAnalyzer.cs
- src/CSharp/CodeCracker/Style/AlwaysUseVarCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/Style/AlwaysUseVarTests.cs
CC0105 is now raised for primitives
> Fixes #407 CC0001 no longer applies to primitives

- src/CSharp/CodeCracker/Design/UseInvokeMethodToFireEventAnalyzer.cs
- test/CSharp/CodeCracker.Test/Design/UseInvokeMethodToFireEventTests.cs
> Fix UseInvokeMethodToFireEvent to work with expression bodied methods

- src/CSharp/CodeCracker/Usage/NoPrivateReadonlyFieldAnalyzer.cs
> Update NoPrivateReadonlyFieldAnalyzer to do not work on generated code

- src/CSharp/CodeCracker/Design/NameOfAnalyzer.cs
- src/CSharp/CodeCracker/Design/NameOfCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Design/NameOfTests.cs
> Fix `nameof` fix to work correctly with methods with non system types

- src/CSharp/CodeCracker/Maintainability/XmlDocumentationAnalyzer.cs
- test/CSharp/CodeCracker.Test/Maintainability/XmlDocumentationTests.cs
> Fix for #624 CC0090 when using /// <inheritdoc/>

- src/CSharp/CodeCracker/Style/AlwaysUseVarAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/AlwaysUseVarTests.cs
This PR fixes #625 
Please check if this is the correct behavior, I was not entirely sure.
> Fixes #625 CC0001 is shown for variables with type dynamic and object

- src/CSharp/CodeCracker/Usage/ReadonlyFieldAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/ReadonlyFieldTests.cs
Closes #621
Also made the analyzer more perfomant by removing OfType and using OfKind instead.
> Fix CC0052 (ReadonlyFieldAnalyzer) false positives

- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedCodeFixProvider.cs
- src/Common/CodeCracker.Common/Extensions/Extensions.cs
- test/CSharp/CodeCracker.Test/Usage/DisposableVariableNotDisposedTests.cs
> Fix disposable not disposed (CC0022) fix when there is chaining

- src/CSharp/CodeCracker/Design/CatchEmptyAnalyzer.cs
- test/CSharp/CodeCracker.Test/Design/CatchEmptyTests.cs
> Fix for #626 CC0003 is shown even for catches which end with throw

- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Usage/DisposableFieldNotDisposedAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/DisposableFieldNotDisposedTests.cs
> Ignore CC0033 when using Dispose pattern

- src/CSharp/CodeCracker/Refactoring/ChangeAnyToAllAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/ChangeAnyToAllCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Refactoring/ChangeAnyToAllTests.cs
- test/Common/CodeCracker.Test.Common/Helpers/Extensions.cs
Diagnostic ids CC0043 and CC0092
Closes #613
> Fix AnyToAll analyzer crash with Elvis op

- src/CSharp/CodeCracker/Refactoring/IntroduceFieldFromConstructorCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Refactoring/IntroduceFieldFromConstructorTest.cs
Refactored version swaps the constructor and then adds a member if needed
> Fix #650 by rearranging the order the tree is modified 

- src/CSharp/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/RemovePrivateMethodNeverUsedAnalyzerTest.cs
I only did the C# part maybe someone else can do the VB part.
> Fix C# part of #526 by excluding the methods with the specified Attributes

- src/CSharp/CodeCracker/Style/PropertyPrivateSetAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/PropertyPrivateSetTests.cs
> #658 Added check to PropertyPrivateSet so it doesn't show when the property is already private.

- test/Common/CodeCracker.Test.Common/Helpers/DiagnosticVerifier.Helper.cs
> fixed comment type, trying to do first pull request

- src/CSharp/CodeCracker/Style/ObjectInitializerCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/ObjectInitializerTests.cs
> Fix ObjectInitializer when there are nested constructor calls

- src/CSharp/CodeCracker/Style/UseStringEmptyAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/UseStringEmptyTests.cs
link fix https://github.com/code-cracker/code-cracker/issues/669
> fix #669 string empty in parameter

- src/CSharp/CodeCracker/Design/UseInvokeMethodToFireEventAnalyzer.cs
- test/CSharp/CodeCracker.Test/Design/UseInvokeMethodToFireEventTests.cs
> Update UseInvokeMethodToFireEventAnalyzer, ignore when checked for null

- src/CSharp/CodeCracker/Design/MakeMethodStaticCodeFixProvider.cs
- src/Common/CodeCracker.Common/Extensions/AnalyzerExtensions.cs
- test/CSharp/CodeCracker.Test/Design/MakeMethodStaticTests.cs
> Fix MakeMethodStaticCodeFixProvider to work with method groups

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Refactoring/AddPropertyToConstructorAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/AddPropertyToConstructorCodeFixProvider.cs
- src/CSharp/CodeCracker/Refactoring/AddPropertyToConstructorCodeFixProviderAll .cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Refactoring/AddPropertyToConstructorTest.cs
> add property to constructor #307

- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Style/StringFormatCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/StringFormatTests.cs
> Fix string interpolation code fix with multiple lines

- src/CSharp/CodeCracker/Style/ForInArrayAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/ForInArrayTests.cs
> Fix change to for when there was an assignment and verify for Enumerable

- src/CSharp/CodeCracker/Design/MakeMethodStaticAnalyzer.cs
- test/CSharp/CodeCracker.Test/Design/MakeMethodStaticTests.cs
> Fix make static analyzer w/ structs

- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Style/SwitchToAutoPropCodeFixProvider.cs
- src/Common/CodeCracker.Common/Extensions/AnalyzerExtensions.cs
- test/CSharp/CodeCracker.Test/Style/SwitchToAutoPropTests.cs
> Fix explicit property when making autoprop

- src/CSharp/CodeCracker/Usage/ReadonlyFieldAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/ReadonlyFieldTests.cs
> Test accessibility when determining if field can be read only.

- src/CSharp/CodeCracker/Usage/DisposableFieldNotDisposedAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/DisposableFieldNotDisposedTests.cs
> Fix DisposableFieldNotDisposedAnalyzer to ignore static fields

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Style/ConsoleWriteLineCodeFixProvider.cs
- src/CSharp/CodeCracker/Style/StringFormatCodeFixProvider.cs
- src/CSharp/CodeCracker/Style/StringFormatFixAllProvider.cs
- test/CSharp/CodeCracker.Test/Style/StringFormatTests.cs
> Fix nested interpolations

- src/CSharp/CodeCracker/Style/SwitchToAutoPropAnalyzer.cs
- src/CSharp/CodeCracker/Style/SwitchToAutoPropCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/SwitchToAutoPropTests.cs
Keep existing modifiers when making an auto property
Closes #699 
Fix switch to auto property with self references
Closes #702
> Fix switch to auto property

- src/CSharp/CodeCracker/Style/ObjectInitializerCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/ObjectInitializerTests.cs
> Fix object initializer fix to not delete statements

- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Refactoring/IntroduceFieldFromConstructorAnalyzer.cs
- src/CSharp/CodeCracker/Refactoring/IntroduceFieldFromConstructorCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Refactoring/IntroduceFieldFromConstructorTest.cs
> Fixe Issue #721

- src/CSharp/CodeCracker/Maintainability/XmlDocumentationAnalyzer.cs
> Fix to do not run CC0090 on generated files

- src/CSharp/CodeCracker/Design/MakeMethodStaticAnalyzer.cs
- test/CSharp/CodeCracker.Test/Design/MakeMethodStaticTests.cs
> Do not make a method static if it takes RoutedEventArgs

- src/VisualBasic/CodeCracker/Extensions/VBAnalyzerExtensions.vb
- src/VisualBasic/CodeCracker/Style/TernaryOperatorCodeFixProviders.vb
- test/Common/CodeCracker.Test.Common/Helpers/Extensions.cs
- test/VisualBasic/CodeCracker.Test/Style/TernaryOperatorTests.vb
> Enable to change to ternary with primitive numeric types (VB)

- src/CSharp/CodeCracker/Usage/UnusedParametersAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/UnusedParametersTests.cs
> Allows verbatim identifiers with UnusedParametersAnalyzer

- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Style/TernaryOperatorCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/TernaryOperatorTests.cs
Fixes #748
Also fixes for type Object
> Enable to change to ternary with primitive numeric types

- src/CSharp/CodeCracker/Performance/RemoveWhereWhenItIsPossibleAnalyzer.cs
- test/CSharp/CodeCracker.Test/Performance/RemoveWhereWhenItIsPossibleTests.cs
> Skip removing Where method when it is called with indexer

- src/CSharp/CodeCracker/Design/CopyEventToVariableBeforeFireCodeFixProvider.cs
- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- test/CSharp/CodeCracker.Test/Design/CopyEventToVariableBeforeFireTests.cs
> Can copy event to variable without crashing when inside a statement

- src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/DisposableVariableNotDisposedTests.cs
> Detect dispose when using elvis operator on CC0022

- src/CSharp/CodeCracker/Usage/CallExtensionMethodAsExtensionAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/CallExtensionMethodAsExtensionTests.cs
Closes #781
Also allows for same tree extension methods to be detected by comparing by method name instead of symbol equality.
> Fixes CallExtensionMethodAsExtensionAnalyzer with C# 5

- src/CSharp/CodeCracker/Usage/ReadonlyFieldAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/ReadonlyFieldTests.cs
Fixes #775 
Analyzer does not create diagnostic if field type is complex value type.
> Fix 'BUG: CC0052 (Make readonly) should not be applied to complex value types #775'

- src/CSharp/CodeCracker/Usage/ReadonlyFieldAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/ReadonlyFieldTests.cs
> Remove ref and out from conditions that allow read only fields

- src/CSharp/CodeCracker/Design/UseInvokeMethodToFireEventAnalyzer.cs
- test/CSharp/CodeCracker.Test/Design/UseInvokeMethodToFireEventTests.cs
> Enhance UseInvokeMethodToFireEventAnalyzer to detect null checks

- src/CSharp/CodeCracker/Usage/CallExtensionMethodAsExtensionAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/CallExtensionMethodAsExtensionTests.cs
> Fix CallExtensionMethodAsExtensionAnalyzer for methods without arguments

- src/CSharp/CodeCracker/Usage/DisposablesShouldCallSuppressFinalizeAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/DisposablesShouldCallSuppressFinalizeTests.cs
> Enable CC0029 analyzer to work with arrow methods

- src/CSharp/CodeCracker/Style/ForInArrayAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/ForInArrayTests.cs
Issued touched assignment, but also checked for pre and post fix unary, ref and out.
Closes #814
> Ignore when iteration variable altered in ForInArrayAnalyzer

- src/CSharp/CodeCracker/CodeCracker.csproj
- src/CSharp/CodeCracker/Design/SwitchWithoutDefaultAnalyzer.cs
- src/CSharp/CodeCracker/Design/SwitchWithoutDefaultCodeFixProvider.cs
- src/Common/CodeCracker.Common/DiagnosticId.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Design/SwicthWithoutDefaultTests.cs
Following the suggestions of the developers in the first PR to resolve the issue # 780, this update has tests for situations of Boolean and integer parameters and treatment of exception CS0151.
> - Fix #780 - Adding more tests and and solve conflicts 

- src/CSharp/CodeCracker/Style/ObjectInitializerAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/ObjectInitializerTests.cs
> Do not offer initializer for dynamic objects (CC0008)

- src/CSharp/CodeCracker/Design/CatchEmptyAnalyzer.cs
- src/VisualBasic/CodeCracker/Design/CatchEmptyAnalyzer.vb
Fixes #839 
Fixed grammer in CatchEmptyAnalyzer
> Fixed grammer in CatchEmptyAnalyzer #839

- src/CSharp/CodeCracker/Performance/StringBuilderInLoopAnalyzer.cs
- src/VisualBasic/CodeCracker/Performance/StringBuilderInLoopAnalyzer.vb
Fixes #839
Update grammar in StringBuilderInLoopAnalyzer.cs #839
Update grammar in StringBuilderInLoopAnalyzer.vb #839
> Fixed grammar in StringBuilderInLoopAnalyzer #839

- src/CSharp/CodeCracker/Design/StaticConstructorExceptionAnalyzer.cs
- src/VisualBasic/CodeCracker/Design/StaticConstructorExceptionAnalyzer.vb
- test/CSharp/CodeCracker.Test/Design/StaticConstructorExceptionTests.cs
Fixes #839
Fixed grammar in StaticConstructorExceptionAnalyzer.cs
Fixed grammar in StaticConstructorExceptionAnalyzer.vb
Updated test in StaticConstructorExceptionTests.cs
> Fixed grammar in StaticConstructorExceptionAnalyzer #839

- src/CSharp/CodeCracker/Usage/RegexAnalyzer.cs
Fixes #839
Update grammar in RegexAnalyzer.cs #839
> Fixed grammar in RegexAnalyzer #839

- src/CSharp/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.cs
- src/VisualBasic/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.vb
Fixes #839
Update grammar in RemovePrivateMethodNeverUsedAnalyzer.cs #839
Update grammar in RemovePrivateMethodNeverUsedAnalyzer.vb #839
> Fixed grammar in RemovePrivateMethodNeverUsedAnalyzer #839

- src/CSharp/CodeCracker/Usage/RethrowExceptionAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/RethrowExceptionTests.cs
Fixes #839
Update grammar in RethrowExceptionAnalyzer.cs #839
Update grammar in RethrowExceptionTests.cs #839
> Fixed grammar in RethrowExceptionAnalyzer #839

- src/CSharp/CodeCracker/Usage/UnusedParametersAnalyzer.cs
- src/VisualBasic/CodeCracker/Usage/UnusedParametersAnalyzer.vb
Fixes #839
Update grammar in UnusedParametersAnalyzer.cs #839
Update grammar in UnusedParametersAnalyzer.vb #839
>  Fixed grammar in UnusedParametersAnalyzer #839

- src/CSharp/CodeCracker/Usage/StringFormatArgsAnalyzer.cs
Fixes #839
Update grammar in StringFormatArgsAnalyzer.cs
> Fixed grammar in StringFormatArgsAnalyzer #839

- src/CSharp/CodeCracker/Usage/IPAddressAnalyzer.cs
- src/VisualBasic/CodeCracker/Usage/IPAddressAnalyzer.vb
Fixes #839
Update grammar in IPAddressAnalyzer.cs #839
Update grammar in IPAddressAnalyzer.vb #839
> Fixed grammar in IPAddressAnalyzer #839

- src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
- src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/DisposableVariableNotDisposedTests.cs
> Fix Expression Bodied members and Yield Return for DisposableVariableNotDisposedAnalyzer

- src/CSharp/CodeCracker/Style/EmptyObjectInitializerAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/EmptyObjectInitializerTests.cs
Fixes #839
Update grammar in EmptyObjectInitializerAnalyzer.cs #839
Update grammar in EmptyObjectInitializerTests.cs #839
> Fixed grammar in EmptyObjectInitializerAnalyzer #839

- src/CSharp/CodeCracker/Style/TaskNameAsyncAnalyzer.cs
Fixes #839
Update grammar in TaskNameAsyncAnalyzer.cs #839
> Fixed grammar in TaskNameAsyncAnalyzer #839

- src/CSharp/CodeCracker/Usage/RethrowExceptionAnalyzer.cs
- test/CSharp/CodeCracker.Test/Usage/RethrowExceptionTests.cs
*  Fixed a very minor spelling error.
> Minor spelling fix

- Hacktoberfest
Hacktoberfest Sign In Sheet 2017!
The goal of this repo is to help beginners who are doing their first pull requests. Feel free to join!
Instruction
In the index file, look for the 'ol' tag. Then insert a 'li' tag with your link to your profile.
Git and Pull Request Resources
Github
The Net Ninja
Awesome-Git
How to Create a Pull Request
Click on the fork on the top to fork this repo.
Go to your repo where you forked the project.
Hit the clone button on your forked repo and copy the given link.
On your terminal / command prompt, type "git clone [put the link here]".
Change the index file in the folder.
Afterward, on your terminal / command prompt, type "git add index.html"; then 'git commit -m "[type a message]" '.
Create a remote to link the repository on github to your local workspace. …
> Hacktoberfest

- Documentation
Code Cracker
An analyzer library for C# and VB that uses Roslyn to produce refactorings, code analysis, and other niceties.
Check the official project site on code-cracker.github.io. There you will find information on how to contribute, our task board, definition of done, definition of ready, etc.
Build status Nuget count License Issues open Coverage Status Source Browser
This is a community project, free and open source. Everyone is invited to contribute, fork, share and use the code. No money shall be charged by this software, nor it will be. Ever.
Installing
You may use CodeCracker in two ways: as an analyzer library that you install with Nuget into your project or as a Visual Studio extension. The way you want to use it depends on the scenario you are working on. You most likely want …
> Documentation

- README.md
I don't see this like a bug. But I see that you also take some minor spelling fix contributions as well here #950
So I'd like to send this as my first PR to this repo. I will fully understand if you don't take such a simple PR like this.
Thks anyways!
> Another minor spelling fix

- README.md
Added a TL;DR for the people who don't like big walls of text. Explains it very simply for newbies like myself to help them choose what they need.
> Add a newbie section to the installation.

- src/CSharp/CodeCracker/Style/TaskNameAsyncAnalyzer.cs
- test/CSharp/CodeCracker.Test/Style/TaskNameASyncTests.cs
Fix Bug: CC0061:#936
obs: sorry for three commits, my bad.
> Implementing interface using async

- test/CSharp/CodeCracker.Test/Refactoring/AllowMembersOrderingAnalyzerTests.cs
We are not referring to the :cat: here
> Not the cat

- src/CSharp/CodeCracker/Style/TaskNameAsyncCodeFixProvider.cs
> Fix issue/958 Don't suggest changes for Async Main

- README.md
Add table of features on the ReadMe so that new users can learn what tools are provided.
Relates to issue #964
> Add list of features to the ReadeMe file

- src/CSharp/CodeCracker.Vsix/source.extension.vsixmanifest
- src/VisualBasic/CodeCracker.Vsix/source.extension.vsixmanifest
Addresses part of issue #964 
Adds release notes pointing to Change log on code-cracker.github.io
> Added release notes to VSIX manifest (C# and VB).

- README.md
- README.pt.md
I still do not know how to rebase and square, sorry.
Fixes #973 .
> readme translated into Brazilian Portuguese

- README.md
There were tons of spelling errors that I spotted in the code. Along with fixing these, I have provided grammatical fixes as well.
> Fixed many spelling and grammar issues

- src/CSharp/CodeCracker/Performance/RemoveWhereWhenItIsPossibleAnalyzer.cs
- test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
- test/CSharp/CodeCracker.Test/Helpers/IQueriableExtensions.cs
- test/CSharp/CodeCracker.Test/Performance/RemoveWhereWhenItIsPossibleTests.cs
Added async extension versions to the analyzer
Fixes #905
> Make CC0011 work with IQueryable and Async methods

- src/CSharp/CodeCracker.Vsix/debug/source.extension.vsixmanifest
- src/CSharp/CodeCracker.Vsix/source.extension.vsixmanifest
- src/VisualBasic/CodeCracker.Vsix/debug/source.extension.vsixmanifest
- src/VisualBasic/CodeCracker.Vsix/source.extension.vsixmanifest
Fixes #1019 .
fix based on this doc: https://madskristensen.net/blog/how-to-upgrade-extensions-to-support-visual-studio-2019/
> VS2019 Support

- src/CSharp/CodeCracker/Style/RemoveTrailingWhitespaceCodeFixProvider.cs
- test/CSharp/CodeCracker.Test/Style/RemoveTrailingWhitespaceTests.cs
> Fixes #923 - BUG: CC0065 "Remove trailing whitespace" bug with pragmas

- src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedAnalyzer.cs
#Info (delete this section)
Please see the [contributing guide](https://github.com/code-cracker/code-cracker/blob/master/README.md#contributing), on the contributing section.
You should notify the maintainers on the issue you are working on before you send a PR.
[Rebase](http://gitready.com/intermediate/2009/01/31/intro-to-rebase.html) and 
[squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your commits.
Submit one commit only, on top of the branch you are working on, `master` for bug fixes to the
stable version, `vnext` to new analyzers and fixers.
Verify if you pass the [definition of done](https://github.com/code-cracker/code-cracker#definition-of-done).
Always reference issue you are fixing (see bellow, e.g. `Fixes #123`)
#Start your PR description …
> Added parser for inline using
