src/CSharp/CodeCracker/Usage/ReadonlyFieldAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/ReadonlyFieldTests.cs

Fixes CC0052 (Make field readonly) to ignore const fields.

Const fields can't be made readonly

---

src/CSharp/CodeCracker/Design/NameOfCodeFixProvider.cs
test/CSharp/CodeCracker.Test/Design/NameOfTests.cs

CC0021 is changing:
```csharp
public class TypeName
{
void Foo(string a, string b)
{
string foo = "b";
}
}
```
To:
```csharp
public class TypeName
{
void Foo(string a, string b)
{
string foo = nameof(a);
}
}
```
The NameOfCodeFixProvider was getting always the first parameter and using its name to create the nameof expression. But we don't need to look at the parameters, because we know the parameter name is equals to the literal to be replaced.

Simplify NameOfCodeFixProvider

---

src/CSharp/CodeCracker/Usage/UriAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/UriAnalyzerTests.cs

This PR make Uri tests work with any culture and also adds a unit test to validate that it won't return a diagnostic for user created classes named Uri.

make tests work with any culture - refs #182

---

src/CSharp/CodeCracker/Style/PropertyPrivateSetAnalyzer.cs
test/CSharp/CodeCracker.Test/Style/PropertyPrivateSetTests.cs

Expression bodied properties don't have an AccessorList, so we need a null check.

Fixes NullReferenceException in CC0047

---

src/CSharp/CodeCracker/Style/ForInArrayAnalyzer.cs
test/CSharp/CodeCracker.Test/Style/ForInArrayTests.cs

Related to #193. When the for condition is not a BinaryExpressionSyntax, tthe code was basically doing
if (!null ?? false) return;
And this caused a NullReferenceException in the line 44.
I just added the parentheses, it fixes the bug. But I don't think it's clear enough, I prefer to change to:
if (condition == null || !condition.IsKind(SyntaxKind.LessThanExpression)) return;
What do you think?

Fix NullReferenceException in ForInArrayAnalyzer (closes #193)

---

src/CSharp/CodeCracker/Usage/IPAddressAnalyzer.cs

@giggio, the IPAdressAnalyzer was using Uri's diagnostic Id. Do you think that could be the source of the error?

IPAdressAnalyzer diagnostic id was wrong. CC0063 instead CC0064 - refs #209

---

src/CSharp/CodeCracker/Usage/UriAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/UriAnalyzerTests.cs

I changed the analyzer to ignore when the arg is null.
I could change MethodChecker to do that always, but since some methods do accept null (arg!), I let this responsibility to the caller.

fixes #209 - BUG on UriAnalyzer

---

runTestsCS.ps1
runTestsVB.ps1
src/CSharp/CodeCracker/Refactoring/AllowMembersOrderingCodeFixProvider.Base.cs
src/CSharp/CodeCracker/Refactoring/AllowMembersOrderingCodeFixProvider.StyleCop.cs
src/CSharp/CodeCracker/Usage/ReadonlyFieldAnalyzer.cs
test/CSharp/CodeCracker.Test/Refactoring/AllowMembersOrderingCodeFixProviderTests.Base.cs
test/CSharp/CodeCracker.Test/Refactoring/AllowMembersOrderingCodeFixProviderTests.StyleCop.cs
test/CSharp/CodeCracker.Test/Verifiers/CodeFixVerifier.cs

https://github.com/code-cracker/code-cracker/issues/172
I created the BaseAllowMembersOrderingCodeFixProvider in order to increase code reuse as more ordering algorithms are expected in the future. 
Each <NameX>AllowMembersOrderingCodeFixProvider should provides a IComparer in order to put the type members on the correct order and the BaseAllowMembersOrderingCodeFixProvider takes the responsibility to write them.

Allow members ordering by style cop patterns (Closes #172)

---

src/CSharp/CodeCracker/Usage/CallExtensionMethodAsExtensionAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/CallExtensionMethodAsExtensionTests.cs

BUG on CC0026: When there is a dynamic don't raise a diagnostic #225

Verify arguments' TypeInfo to identify dynamic arguments

---

src/CSharp/CodeCracker/Usage/RethrowExceptionAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/RethrowExceptionTests.cs

Targeting BUG on CC0012: RethrowExceptionAnalyzer throwing "Sequence
contains no elements"

throw expression must be inside a catch block

---

src/CSharp/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/RemovePrivateMethodNeverUsedAnalyzerTest.cs

Fix RemovePrivateMethodNeverUsed to correctly identify all references to the private method.
This code causes CC0068:
````csharp
using System;
public class Foo
{
public void PublicFoo()
{
Action method = PrivateFoo;
}
private void PrivateFoo() { }
}
````
The PrivateFoo method can't be removed in this context.
(This also affects PR #284)

Fix RemovePrivateMethodNeverUsed

---

src/VisualBasic/CodeCracker/Design/NameOfCodeFixProvider.vb
test/CSharp/CodeCracker.Test/Design/NameOfTests.cs
test/CSharp/CodeCracker.Test/Refactoring/SplitIntoNestedIfTests.cs
test/CSharp/CodeCracker.Test/Usage/DisposableVariableNotDisposedTests.cs
test/CSharp/CodeCracker.Test/Usage/RemoveUnreachableCodeTest.cs
test/Common/CodeCracker.Test.Common/Verifiers/CodeFixVerifier.cs
test/VisualBasic/CodeCracker.Test/Design/NameOfTests.vb

Fixes #309
Also creates infrastructure for fix all verification for VB which was missing.

Enable fix all for nameof code fix for vb

---

src/CSharp/CodeCracker/Style/ObjectInitializerAnalyzer.cs
src/CSharp/CodeCracker/Style/ObjectInitializerCodeFixProvider.cs
test/CSharp/CodeCracker.Test/Style/ObjectInitializerTests.cs

Fixes #315
For some reason we were not checking if the assignment was an `ObjectCreationExprssionSyntax`. Fixed now.
Also fixes errors on the word 'assignment'.
Also add a test to make sure it doesn't happen on `CC0008`. It doesn't.

Fix bug on object creation for CC0009 (ObjectInitializerAnalyzer)

---

test/CSharp/CodeCracker.Test/ChangeCultureTests.cs
test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
test/CSharp/CodeCracker.Test/Refactoring/ComputeExpressionTests.cs
test/Common/CodeCracker.Test.Common/ChangeCulture.cs
test/Common/CodeCracker.Test.Common/CodeCracker.Test.Common.csproj
test/Common/CodeCracker.Test.Common/Helpers/CodeFixVerifier.Helper.cs
test/Common/CodeCracker.Test.Common/Helpers/DiagnosticVerifier.Helper.cs
test/Common/CodeCracker.Test.Common/Verifiers/CodeFixVerifier.cs
test/Common/CodeCracker.Test.Common/Verifiers/DiagnosticVerifier.cs

Closes #313, which describes the issue in more detail.
It adds the `ChangeCulture` class which changes the current culture
during a test. It enables testing on specific cultures, that were harder
to test before. It is a simple wrap on the current culture property on
the current thread.
I also added on every await on the base and helper test classes a
`.ConfigureAwait(true)` so that every test always returns on the same
thread as it started. If we did not do this then the thread that
continues a test may be different from the one that started it, causing
a problem on the current culture setting.

Allow to change culture in a test

---

src/CSharp/CodeCracker/Usage/CallExtensionMethodAsExtensionAnalyzer.cs
src/CSharp/CodeCracker/Usage/CallExtensionMethodAsExtensionCodeFixProvider.cs
src/Common/CodeCracker.Common/Extensions/AnalyzerExtensions.cs
test/CSharp/CodeCracker.Test/Usage/CallExtensionMethodAsExtensionTests.cs

closes #262
Verifying on a speculative model if selected overload would change and not even raising analyzer.
Changes in code fix are not related to the bug, but are refactorings. The focus of the update is the analyzer, that is not raising the diagnostic anymore.

Fix bug where selected overload would change on CC0026

---

src/CSharp/CodeCracker/Usage/StringFormatArgsAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/StringFormatArgsTests.cs

This PR fixes issue #333 and #330. 
- CC0056 no longer classifies a valid format string as a faulty one.
- Added 3 new test to cover the scenario described in the issue. 
- Tested both with and without format specifiers, `{0}` and `{0:P}`.

Fix bug where CC0056 classifies a valid format string as a faulty one.

---

src/CSharp/CodeCracker/Design/NameOfAnalyzer.cs
src/CSharp/CodeCracker/Design/NameOfCodeFixProvider.cs
test/CSharp/CodeCracker.Test/Design/NameOfTests.cs

Regarding to #198 I added tests to NameOfCodeFixProvider with verbatim identifier.
It turns out that NameOf doesn't work correctly with verbatim identifier.
NameOfCodeFixProvider changed this code:
```csharp
void Foo(string @for)
{
string whatever = "for";
}
```
to following:
```csharp
void Foo(string @for)
{
string whatever = nameof(for);
}
```
So I changed NameOfCode(Analyzer/FixProvider) to take nameof argument from identifier that the string literal refers and now NameOf seems working correctly.

Test with verbatim identifier NameOfCodeFixProvider (#198)

---

src/CSharp/CodeCracker/Usage/StringFormatArgsAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/StringFormatArgsTests.cs

Discussed in #335, I have extended the StringFormatArgsAnalyzer to also identify invalid format strings.

CC0056 Identify invalid format strings

---

src/CSharp/CodeCracker/Design/NameOfAnalyzer.cs
src/Common/CodeCracker.Common/Extensions/AnalyzerExtensions.cs
test/CSharp/CodeCracker.Test/Design/NameOfTests.cs

Fixes C# part of #263 
Changed C# NameOfAnalyzer to work with any scope.
Now NameOfAnalyzer first check if string literal is in method/constructor/indexer and tries to find match in parameters list.
If that fails semantic model is used to lookup symbols/namespaces.

C# CC0021 analyzer expand scope

---

README.md

Added -Pre parameter to Install-Package. 
Missing this parameter will get an exception.
```
At line:1 char:1
+ install-package CodeCracker.CSharp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

Missing parameter when installing through Nuget

---

src/CSharp/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/RemovePrivateMethodNeverUsedAnalyzerTest.cs

The first commit is better to analyze the PR. The 2nd one is to update from tabs to spaces, the file was incorrectly formatted.
Closes #343.

Update RemovePrivateMethodNeverUsed to work with generic methods

---

src/CSharp/CodeCracker/CodeCracker.csproj
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityCodeFixProvider.cs
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInMethodParameter.cs
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInMethodReturnType.cs
src/Common/CodeCracker.Common/Extensions/AnalyzerExtensions.cs
src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
src/Common/CodeCracker.Common/Properties/Resources.resx
test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
test/CSharp/CodeCracker.Test/Design/InconsistentAccessibilityTests.MethodParameter.cs
test/CSharp/CodeCracker.Test/Design/InconsistentAccessibilityTests.MethodReturnType.cs

Fixes `CS0050` in #381 
I added `CS0050` to `InconsistentAccessibilityCodeFixProvider` with unit tests.
Also changed code action messages to use localizable strings.
Common methods used by `InconsistentAccessibilityInMethodParameter/(ReturnType)` were moved as extension methods.

CS0050 code fix

---

src/CSharp/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/RemovePrivateMethodNeverUsedAnalyzerTest.cs

Fixes CC0068 on #368
I've created and called a new method 'IsMainMethodEntryPoint' that verifies:
Method name is "Main";
Method is static;
Method returns 'Void' or 'Int32';
Method has more than 1 parameters;
Method has no parameter
Method has parameter type 'String[]'
And added respectives tests.

Fix bug on CC0068 (RemovePrivateMethodNeverUsed) with Main #368

---

src/CSharp/CodeCracker/CodeCracker.csproj
src/CSharp/CodeCracker/Style/ConsoleWriteLineAnalyzer.cs
src/CSharp/CodeCracker/Style/ConsoleWriteLineCodeFixProvider.cs
src/CSharp/CodeCracker/Style/StringFormatAnalyzer.cs
src/CSharp/CodeCracker/Style/StringFormatCodeFixProvider.cs
src/Common/CodeCracker.Common/DiagnosticId.cs
src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
src/Common/CodeCracker.Common/Properties/Resources.resx
test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
test/CSharp/CodeCracker.Test/Style/ConsoleWriteLineTests.cs

Closes #380
Already using localization
Updated String.Format analyzer and code fix to use localization
and to the more performant code action.
Using common code for string.format and console.writeline.

Add string interpolation to Console.WriteLine

---

src/CSharp/CodeCracker/Design/NameOfAnalyzer.cs
test/CSharp/CodeCracker.Test/Design/NameOfTests.cs

Bug fix for #359. 
---
**Changes:**
- Added a check if the node is within a `VariableDeclaratorSyntax` or a `PropertyDeclarationSyntax`
- Added 2 new unit test to cover these cases.
I think this should fix the issue, maybe I am forgetting some edge case.

BugFix nameof analyzer (CC0021)

---

src/CSharp/CodeCracker/Style/ObjectInitializerCodeFixProvider.cs
test/CSharp/CodeCracker.Test/Style/ObjectInitializerTests.cs

Fixed bug on ObjectInitializerCodeFixProvider when constructor already has initialization
Fix #396

Fixed bug on ObjectInitializerCodeFixProvider

---

src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/DisposableVariableNotDisposedTests.cs

Fixed the ```DisposableVariableNotDisposedAnalyzer``` so it ignores nodes
whose Parents are of type ```ReturnStatementSyntax```
Closes #399.

Ignore Disposable objects created on return statements

---

src/CSharp/CodeCracker/Style/ForInArrayAnalyzer.cs
src/CSharp/CodeCracker/Style/ForInArrayCodeFixProvider.cs
test/CSharp/CodeCracker.Test/Style/ForInArrayTests.cs

This PR Fix #318
Now CC0006 can deal with more array accessors, like this:
````csharp
var array = new [] {1};
var count = 0;
for (var i = 0; i < array.Length; i++)
{
var item = array[i];
count += array[i];
Console.WriteLine(array[i]);
count += array[array[i]];
}
````
CodeFix change old code to:
````csharp
var array = new [] {1};
var count = 0;
foreach (var item in array)
{
count += item;
Console.WriteLine(item);
count += array[item];
}
````

Expanded CC0006 to deal with more array accessors

---

src/CSharp/CodeCracker/CodeCracker.csproj
src/CSharp/CodeCracker/Maintainability/XmlDocumentationAnalyzer.cs
src/CSharp/CodeCracker/Maintainability/XmlDocumentationCodeFixProvider.cs
src/CSharp/CodeCracker/Maintainability/XmlDocumentationCreateMissingParametersCodeFixProvider.cs
src/CSharp/CodeCracker/Maintainability/XmlDocumentationRemoveNonExistentParametersCodeFixProvider.cs
src/Common/CodeCracker.Common/DiagnosticId.cs
src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
src/Common/CodeCracker.Common/Properties/Resources.resx
test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
test/CSharp/CodeCracker.Test/Style/XmlDocumentationAnalyzerTests.cs

I created analyzer and 2 code fixes, one for missing parameters and another to unexisting parameters.
Tests are ok, but I am facing a problem when testing running VS 
But when I press <kbd>CTRL</kbd>+<kbd>.</kbd> I get a error in VS.
**"One or more erros ocurred."**
When I checked to see all exceptions in VS I got StackTrace and got this exception:
````
System.InvalidCastException occurred
Message: Exception thrown: 'System.InvalidCastException' in mscorlib.dll
Additional information: Unable to cast object of type 'System.Reflection.RuntimeMethodInfo' to type 'System.Reflection.ConstructorInfo'.
````
I tried a lot things, but couldnt fix, I need help.
Fix #357

Implemented analyzer to fix xml docs parameters

---

src/CSharp/CodeCracker/Design/NameOfAnalyzer.cs
test/CSharp/CodeCracker.Test/Design/NameOfTests.cs

Nameof now ignores not yet declared locals
---
This PR fixes #408.
Changes:
- Check if the symbol is a local and if so make sure that it is declared before the string.
-
Sorry for not letting you know I was working on it, just started on it tonight. If a issue takes me more than couple of hours to finish I will ask if I can work on it :+1:

Fix #408. Nameof now ignores not yet declared locals

---

src/CSharp/CodeCracker/Style/TaskNameAsyncAnalyzer.cs
test/CSharp/CodeCracker.Test/Style/TaskNameASyncTests.cs

Ensure async methods with the new or overrides modifier are not flagged to be renamed by the TaskNameAsyncAnalyzer.

Fix #424 forTaskNameAsyncAnalyzer with new or overrides modifiers

---

src/CSharp/CodeCracker/Usage/DisposablesShouldCallSuppressFinalizeAnalyzer.cs
src/VisualBasic/CodeCracker/Usage/DisposablesShouldCallSuppressFinalizeAnalyzer.vb
test/CSharp/CodeCracker.Test/Usage/DisposablesShouldCallSuppressFinalizeTests.cs
test/VisualBasic/CodeCracker.Test/Usage/DisposablesShouldCallSuppressFinalizeTests.vb

Added an extra cast to both the C# and VB analyzers.  Also had to get the statements of this dispose for VB a bit differently.  It was always returning Nothing with the previous code because it was getting a declaration node, which does not include the statements, instead of a method block node that does contain the statements.

Fix #452 for both CSharp and VB with proper casting.

---

src/CSharp/CodeCracker/Design/NameOfAnalyzer.cs
src/CSharp/CodeCracker/Design/NameOfCodeFixProvider.cs
src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedAnalyzer.cs
src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedCodeFixProvider.cs
src/Common/CodeCracker.Common/Extensions/AnalyzerExtensions.cs
test/CSharp/CodeCracker.Test/Usage/DisposableVariableNotDisposedTests.cs

Potental Fix for #432.
Changes
-
- Added two checks to not raise when used in 
- ThisConstructorInitializer, ```Foo() : this(new DisposableObject())```
- ObjectCreationExpression ```new Bar(new DisposableObject())```
- Expanded the Code Fix to also provide a fix for disposable object passed as arguments.
```CSharp
string.Format(string.Empty,new Disposable());
// Becomes:
using (var disposable = new Disposable())
{
string.Format(string.Empty, disposable);
}
```

Fix #432. Disposable Instantiation on constructor call 

---

src/CSharp/CodeCracker/Refactoring/IntroduceFieldFromConstructorAnalyzer.cs
src/CSharp/CodeCracker/Style/RemoveAsyncFromMethodAnalyzer.cs
src/CSharp/CodeCracker/Usage/RethrowExceptionAnalyzer.cs
src/VisualBasic/CodeCracker/Refactoring/ParameterRefactoryAnalyzer.vb

I noticed some analyzers had the wrong Help link Uri, so I fixed them.
Since this is a simple fix I used the `master` branch. If this should be on `vnext` just let me know and I'll redo.

Fixes incorrect help links from Analyzers

---

src/CSharp/CodeCracker/CodeCracker.csproj
src/CSharp/CodeCracker/Style/PreferAnyToCountGreaterThanZeroAnalyzer.cs
src/CSharp/CodeCracker/Style/PreferAnyToCountGreaterThanZeroCodeFixProvider.cs
src/Common/CodeCracker.Common/DiagnosticId.cs
src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
src/Common/CodeCracker.Common/Properties/Resources.resx
src/VisualBasic/CodeCracker/CodeCracker.vbproj
src/VisualBasic/CodeCracker/Style/PreferAnyToCountGreaterThanZeroAnalyzer.vb
src/VisualBasic/CodeCracker/Style/PreferAnyToCountGreaterThanZeroCodeFixProvider.vb
test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
test/CSharp/CodeCracker.Test/Style/PreferAnyToCountGreaterThanZeroTests.cs
test/VisualBasic/CodeCracker.Test/CodeCracker.Test.vbproj
test/VisualBasic/CodeCracker.Test/Style/PreferAnyToCountGreaterThanZeroTests.vb

Implemented this code fix for `Count() > 0` and `Count > 0` in C# and VB

Add PreferAnyToCountGreaterThanZero Analyzer, closes #490

---

src/CSharp/CodeCracker/CodeCracker.csproj
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityCodeFixProvider.cs
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInOperatorParameter.cs
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInOperatorReturnType.cs
src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
src/Common/CodeCracker.Common/Properties/Resources.resx
test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
test/CSharp/CodeCracker.Test/Design/InconsistentAccessibilityTests.OperatorParameter.cs
test/CSharp/CodeCracker.Test/Design/InconsistentAccessibilityTests.OperatorReturnType.cs

Fixes `CS0056` and `CS0057` in #381.
Implementation with tests for [CS0056](https://msdn.microsoft.com/en-us/library/7zdw9dt0%28v=vs.90%29.aspx) and [CS0057](https://msdn.microsoft.com/en-us/library/1he6k2zs%28v=vs.90%29.aspx) compiler error numbers.
@giggio, please take a look because it's been a while since I made a pull request to code-cracker. Let me know if anything. 
Thanks :+1: !

CS0056 & CS0057 code-fix

---

src/CSharp/CodeCracker/CodeCracker.csproj
src/CSharp/CodeCracker/Design/InconsistentAccessibility/AccessibilityDomainChecker.cs
src/CSharp/CodeCracker/Design/InconsistentAccessibility/IInconsistentAccessibilityCodeFix.cs
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityCodeFix.cs
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityCodeFixProvider.cs
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInDelegateParameterType.cs
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInDelegateReturnType.cs
src/CSharp/CodeCracker/Design/InconsistentAccessibility/InconsistentAccessibilityInMethodParameter.cs
src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
src/Common/CodeCracker.Common/Properties/Resources.resx
test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
test/CSharp/CodeCracker.Test/Design/InconsistentAccessibilityTests.AccessibilityDomainChecker.cs
test/CSharp/CodeCracker.Test/Design/InconsistentAccessibilityTests.Delegate.cs
test/CSharp/CodeCracker.Test/Design/InconsistentAccessibilityTests.OperatorReturnType.cs
test/Common/CodeCracker.Test.Common/Helpers/DiagnosticVerifier.Helper.cs

Fixes `CS0058` and `CS0059` in #381.
Implementation with tests for `CS0058` and `CS0059` compiler error numbers.
Additionally I added checking if reason for inconsistent accessibility is in accessibility domain instead of actual accessibility modifiers of type in cause of nested types.
I created a `CreateDocument` method overload without `LanguageVersion` for `VisualBasic` in `DiagnosticVerifier.cs` because I wanted to avoid draging dependency to `..CodeAnalysis.VisualBasic` for `CodeCracker.Test` `C#` project

CS0058 & CS0059 code-fix

---

src/CSharp/CodeCracker/Usage/UnusedParametersCodeFixProvider.cs
src/VisualBasic/CodeCracker/Usage/UnusedParametersCodeFixProvider.vb
test/CSharp/CodeCracker.Test/Usage/UnusedParametersTests.cs
test/VisualBasic/CodeCracker.Test/CodeCracker.Test.vbproj
test/VisualBasic/CodeCracker.Test/Usage/UnusedParametersTests.vb

Closes #539 for both VB and C#

Fix UnusedParametersCodeFixProvider crashing when removing params

---

src/CSharp/CodeCracker/CodeCracker.csproj
src/CSharp/CodeCracker/Usage/InconsistentParameterDefaultValueAnalyzer.cs
src/CSharp/CodeCracker/Usage/InconsistentParameterDefaultValueCodeFixProvider.cs
src/Common/CodeCracker.Common/DiagnosticId.cs
src/Common/CodeCracker.Common/Properties/Resources.Designer.cs
src/Common/CodeCracker.Common/Properties/Resources.resx
test/CSharp/CodeCracker.Test/CodeCracker.Test.csproj
test/CSharp/CodeCracker.Test/Maintainability/InconsistentParameterDefaultValueTests.cs

Supports the following scenarios:
- overriding a method from the base class
- implicitly implementing an interface method
- explicitly implementing an interface method

Fix #575: CC0110

---

test/Common/CodeCracker.Test.Common/ChangeCulture.cs

Some tests in ValidateColorTests were failing in French culture. This is because `"200,100,50"` is a valid color in English, but not in French, because the list separator is different. See the comments [here](https://github.com/code-cracker/code-cracker/issues/1#issuecomment-154075860) for details.
I made a few changes to the `ChangeCulture` class:
- set the `DefaultThreadCurrentCulture` and `DefaultThreadCurrentUICulture` properties so that the new culture also applies to other threads in async code
- save the original values to be able to restore them later

Fix failing ValidateColor tests in some cultures

---

src/CSharp/CodeCracker/Usage/StringFormatArgsAnalyzer.cs
src/Common/CodeCracker.Common/DiagnosticId.cs
test/CSharp/CodeCracker.Test/Usage/StringFormatArgsTests.cs

Fixes #585
StringFormatArgsAnalyzer was always raising an error, when it is not an
error to have extra parameters. So we have taken an extra id, CC0111 to
use as the warning, when string.Format is being provided more arguments
than the format string is requiring.
This will now raise a warning:
string.Format("{0}", "a", "b");
When string.Format has less arguments than the format string requires,
we are still raising CC0056, as an error, as it will generate a
runtime error.
This will now raise an error:
string.Format("{0}{1}", "a");
Other verifications the analyzer was already checking continue as
before.

Reorganize StringFormatArgsAnalyzer to use the correct severities

---

src/CSharp/CodeCracker/Usage/ReadonlyFieldAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/ReadonlyFieldTests.cs

Closes #610
Related to https://github.com/dotnet/roslyn/issues/7173

Fixes ReadonlyFieldAnalyzer when reporting diagnostic on incorrect type

---

src/CSharp/CodeCracker/Refactoring/ChangeAnyToAllAnalyzer.cs
src/CSharp/CodeCracker/Refactoring/ChangeAnyToAllCodeFixProvider.cs
test/CSharp/CodeCracker.Test/Refactoring/ChangeAnyToAllTests.cs

This PR fixes 2 things  for ChangeAnyToAllAnalyzer:
* negated expressions, closes #640
* expression bodied methods, closes #641
See tests.

Fix ChangeAnyToAllAnalyzer for negated expressions and expression bodied methods

---

src/CSharp/CodeCracker/Usage/DisposableFieldNotDisposedAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/DisposableFieldNotDisposedTests.cs

Closes #638
Also refactor CallsDisposeOnField to protect against possible other null reference exceptions.

Enable DisposableFieldNotDisposedAnalyzer to work with expression bodied methods

---

src/CSharp/CodeCracker/Usage/UnusedParametersAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/UnusedParametersTests.cs

Closes #646
Also enable use on expression bodied methods.

Ignore method groups when checking for unused parameters

---

src/CSharp/CodeCracker/Usage/VirtualMethodOnConstructorAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/VirtualMethodOnConstructorTests.cs

Closes #712
Also fixes tests that had incorrect `{{` or `}}`.

Fixes VirtualMethodOnConstructorAnalyzer to check params

---

src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/DisposableVariableNotDisposedTests.cs

Passed to methods.
Assigned to properties.
Fixes #465

Ignore Disposable Variable when object could live longer

---

src/VisualBasic/CodeCracker/Style/TernaryOperatorAnalyzer.vb
src/VisualBasic/CodeCracker/Style/TernaryOperatorCodeFixProviders.vb
test/VisualBasic/CodeCracker.Test/Style/TernaryOperatorTests.vb

Closes #725 for CC0013
Also enables it to work with ternaries when they have leading trivia.
Also added the missing namespace to the test file.

Fix Make Ternary for VB when it has comments

---

src/CSharp/CodeCracker/Refactoring/MergeNestedIfCodeFixProvider.cs
test/CSharp/CodeCracker.Test/Refactoring/MergeNestedIfTest.cs

Closes #740
Fixing for Logical OR, Conditional and Coalescing.

Respect precendence rules when nesting if statements

---

src/CSharp/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.cs
src/VisualBasic/CodeCracker/Usage/RemovePrivateMethodNeverUsedAnalyzer.vb
test/CSharp/CodeCracker.Test/Usage/RemovePrivateMethodNeverUsedAnalyzerTest.cs
test/VisualBasic/CodeCracker.Test/Usage/RemovePrivateMethodNeverUsedAnalyzerTest.vb

Fixes #744
Also, fixes on C# when qualified names were not verified
Also, check for entry points in VB (already worked, only tests)

Enable attributes when ignoring private methods in VB

---

src/CSharp/CodeCracker/Usage/DisposablesShouldCallSuppressFinalizeAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/DisposablesShouldCallSuppressFinalizeTests.cs

Fixes #776
DisposablesShouldCallSuppressFinalizeAnalyzer did not find GC.SuppressFinalize(this) in code blocks. Now it checks for GC.SuppressFinalize(this) in any block - finally/if etc.
I added proper tests to check this issue.

Fix 'GC.SuppressFinalize within the finally block' #776

---

src/CSharp/CodeCracker/Usage/DisposableFieldNotDisposedAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/DisposableFieldNotDisposedTests.cs

Enable fields to be disposed when using member access expression

---

src/CSharp/CodeCracker/Usage/ReadonlyFieldAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/ReadonlyFieldTests.cs

Fix #812
Add constructor to the top of the list so we add fields with constructors initializers first

Ignore member order on ReadonlyFieldAnalyzer

---

src/CSharp/CodeCracker/Design/MakeMethodStaticAnalyzer.cs
src/CSharp/CodeCracker/Extensions/CSharpAnalyzerExtensions.cs
src/CSharp/CodeCracker/Style/TaskNameAsyncAnalyzer.cs
test/CSharp/CodeCracker.Test/Style/TaskNameASyncTests.cs

Fix #793
Also, refactor the search for interface members on TaskNameAsyncAnalyzer and MakeMethodStaticAnalyzer.

Ignore methods that implement interface in TaskNameAsync (CC0061)

---

src/CSharp/CodeCracker/Performance/StringBuilderInLoopAnalyzer.cs
test/CSharp/CodeCracker.Test/Performance/StringBuilderInLoopTests.cs

If the member access is to a variable declared within the loop, we should not be raising a diagnostic.
Fix #797

Update StringBuilderInLoopAnalyzer to ignore some member accesses

---

src/VisualBasic/CodeCracker/Style/TernaryOperatorCodeFixProviders.vb
test/VisualBasic/CodeCracker.Test/Style/TernaryOperatorTests.vb

Fixes #798
The original code was able to handle a combination of simple and non-simple assignment operators if the simple one was on the if and the complex one on the else. I have amended the code so that the opposite case can be handled as well. The changes should also work if there are two different non-simple assignment operators on if and else.
Tests have been added for all the described scenarios.
I've encountered an issue whilst applying the fix for which I don't have a clear answer. On line 140 I wasn't able to call SyntaxFactory.Token(SyntaxKind.SimpleAssignmentStatement) as it would throw a System.ArgumentOutOfRangeException, but it builds and passes the tests with an EqualsToken. I'm not sure why this is the case.
Please let me know if any further amendment is needed.
Thanks.

Fixes #798

---

src/CSharp/CodeCracker/Usage/ReadonlyFieldAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/ReadonlyFieldTests.cs

Fixes #853
Related to #544 but in that issue the variable was not initialized.

Fix MakeReadonly with lambdas when field has initializer

---

src/CSharp/CodeCracker/Usage/UnusedParametersAnalyzer.cs
test/CSharp/CodeCracker.Test/Usage/UnusedParametersTests.cs

CC0057 UnusedParametersAnalyzer should not be triggered on virtual methods
Includes test case and fix.
Fixes #872

Fix #872: UnusedParametersAnalyzer

---

src/CSharp/CodeCracker/Usage/AbstractClassShouldNotHavePublicCtorsAnalyzer.cs

Fixes #839
Update grammar in AbstractClassShouldNotHavePublicCtorsAnalyzer.cs #839

Fixed grammar in AbstractClassShouldNotHavePublicCtorsAnalyzer #839

---

src/CSharp/CodeCracker/Design/UseInvokeMethodToFireEventAnalyzer.cs
test/CSharp/CodeCracker.Test/Design/UseInvokeMethodToFireEventTests.cs

Fixes #926.
Replaces PR #941.
Sorry for the confusion with the this PR.

CC0031 Bug 926 check for null misses constructor

---

src/CSharp/CodeCracker/Performance/RemoveWhereWhenItIsPossibleAnalyzer.cs
src/CSharp/CodeCracker/Style/TaskNameAsyncCodeFixProvider.cs
test/CSharp/CodeCracker.Test/Style/TaskNameASyncTests.cs

Adding an "Async" method suffix should remove any embedded "Async" string

---

src/CSharp/CodeCracker/Style/ConvertLambdaExpressionToMethodGroupAnalyzer.cs
test/CSharp/CodeCracker.Test/Style/ConvertLambdaExpressionToMethodGroupTests.cs

Fixes #930 by checking if the calling method has generic type definitions. There could be cases that the generic type can be inferred but I'm not checking for that.

Fixes #930 CC0020 cannot be used when types are declared

---

README.md

This PR inserts a missing link in the readme to issue #66, like it is done for all other referenced issues in the readme.

Insert missing link to Issue #66 in readme.md

---

src/CSharp/CodeCracker/Design/StaticConstructorExceptionCodeFixProvider.cs
src/CSharp/CodeCracker/Maintainability/XmlDocumentationMissingInCSharpCodeFixProvider.cs
src/CSharp/CodeCracker/Maintainability/XmlDocumentationMissingInXmlCodeFixProvider.cs
src/CSharp/CodeCracker/Refactoring/StringRepresentationCodeFixProvider.cs

Fixes #1032.
This PR adds missing property name `Name` to `ExportCodeFixProviderAttribute`.

Add property name 'Name' to ExportCodeFixProviderAttribute.
